name: work_today
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  firebase_messaging: ^7.0.3
  flutter:
    sdk: flutter
  flutter_auth_buttons: ^0.10.0
  geolocator: ^5.3.1
  google_fonts: ^1.1.2
  google_sign_in: ^4.5.6
  modal_progress_hud: ^0.1.3
  theme_provider: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/user.png

  fonts:
    - family: 'FV_ALMELO'
      fonts:
        - asset: assets/fonts/FV_Almelo.ttf

    - family: 'OleoScript'
      fonts:
        - asset: fonts/OleoScript-Regular.ttf

    - family: 'Indie'
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf

    - family: 'Dancing'
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
